name: docs
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      work:
        description: 작업 트리거
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: npm 7
        run: npm i -g npm@7
      - name: install core dependency
        run: |
          npm ci
      - name: build docusaurus
        working-directory: docs
        run: |
          npm ci
          npm run build
        env:
          KAKAOMAP_API_KEY: ${{ secrets.KAKAOMAP_API_KEY }}
          NODE_ENV: development
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build
          cname: react-kakao-maps-sdk.jaeseokim.dev
