name: docs
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      work:
        description: 작업 트리거
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm build
      - run: |
          npm install
          npm run build
      - env:
          KAKAOMAP_API_KEY: ${{ secrets.KAKAOMAP_API_KEY }}
          NODE_ENV: development
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          cname: react-kakao-maps-sdk.jaeseokim.dev
