name: Delete Environment (default settings)

on:
  workflow_dispatch:
    inputs:
      work:
        description: 작업 트리거
        required: false

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.TOKEN }}
          environment: Production
